security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory:
            memory:
                users:
#                    admin:
#                        password: 1234
#                        roles: 'ROLE_ADMIN'
#                    editor:
#                        password: 1234
#                        roles: 'ROLE_USER'
        db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            provider: db_provider
    access_control:
        - { path: ^/backend, roles: ROLE_ADMIN }